# Generated by Django 4.1.3 on 2022-12-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_itemdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdb',
            old_name='Username',
            new_name='Description',
        ),
    ]
