# Generated by Django 4.1.3 on 2022-12-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_prodb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodb',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
