# Generated by Django 4.1.3 on 2022-12-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logdb',
        ),
    ]
