# Generated by Django 4.1.3 on 2022-12-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_delete_logdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regdb',
            new_name='registerdb',
        ),
    ]
