# Generated by Django 4.1.3 on 2022-12-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_rename_regdb_registerdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdb',
            old_name='cpassword',
            new_name='confirmpassword',
        ),
    ]
